name: superduper
description: An app for super bikes
publish_to: "none"
version: 0.2.4+31

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.0
  flutter_foreground_task: ^6.0.0
  flutter_markdown: ^0.6.13
  flutter_reactive_ble: ^5.0.3
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  json_annotation: ^4.8.0
  permission_handler: ^10.2.0
  riverpod_annotation: ^2.0.0
  unique_name_generator: ^1.0.0
  url_launcher: ^6.1.8
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/superduper-nobg.png

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#DBECF0"
  adaptive_icon_foreground: "assets/superduper_android.png"
  ios: true
  image_path: "assets/superduper_android.png"
  image_path_ios: "assets/superduper.png"
  remove_alpha_ios: true
